import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
import type { Metadata } from "next";

export const metadata: Metadata = {
  metadataBase: new URL("https://petranusa.my.id"),

  title: {
    default: "PT Petratama Abdi Nusa",
    template: "%s | PT Petratama Abdi Nusa",
  },

  description:
    "Certification, In House Training, Consultancy dan Public Course untuk industri migas, energi, dan profesional.",

  keywords: [
    "sertifikasi",
    "training",
    "consultancy",
    "migas",
    "geothermal",
    "PT Petratama Abdi Nusa",
  ],

  openGraph: {
    title: "PT Petratama Abdi Nusa",
    description:
      "Certification, Training & Consultancy.",
    url: "https://petranusa.my.id",
    siteName: "PT Petratama Abdi Nusa",
    images: ["/og-image.jpg"],
    locale: "id_ID",
    type: "website",
  },
};
      }
    ]
  }
};
