import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "PT Petratama Abdi Nusa",
  description:
    "Certification, Training, Consultancy and Public Course.",

  keywords: [
    "sertifikasi",
    "training",
    "consultancy",
    "kursus",
    "PT Petratama Abdi Nusa"
  ],

  openGraph: {
    title: "PT Petratama Abdi Nusa",
    description:
      "Certification, Training, Consultancy and Public Course.",

    url: "https://petranusa.my.id",

    siteName: "PT Petratama Abdi Nusa",

    images: [
      {
        url: "/og-image.jpg",
        width: 1200,
        height: 630
      }
    ]
  }
};
